# Generated by Django 5.1.15 on 2026-09-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.TextField(blank=True, null=True, verbose_name='URL Foto Profil / External Avatar'),
        ),
    ]
