# Generated by Django 5.1.15 on 2026-08-28 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaporanLiterasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_bacaan', models.CharField(max_length=255, verbose_name='Judul Buku / Artikel')),
                ('penulis', models.CharField(blank=True, max_length=200, verbose_name='Penulis / Sumber')),
                ('rangkuman', models.TextField(verbose_name='Rangkuman / Refleksi')),
                ('word_count', models.PositiveIntegerField(default=0, verbose_name='Jumlah Kata')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Diverifikasi Guru')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laporan_literasi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Laporan Literasi RESIK',
                'verbose_name_plural': 'Daftar Laporan Literasi RESIK',
                'ordering': ['-created_at'],
            },
        ),
    ]
