# Generated by Django 5.1.15 on 2026-08-28 23:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('literasi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiterasiReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField(default=1, verbose_name='Minggu Ke-')),
                ('report_date', models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Literasi')),
                ('book_title', models.CharField(max_length=255, verbose_name='Judul Buku / Sumber Bacaan')),
                ('author', models.CharField(max_length=255, verbose_name='Penulis / Pengarang')),
                ('publisher', models.CharField(blank=True, max_length=255, verbose_name='Penerbit')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Kota Terbit')),
                ('year', models.CharField(blank=True, max_length=10, verbose_name='Tahun Terbit')),
                ('page_count', models.CharField(blank=True, max_length=50, verbose_name='Jumlah / Rentang Halaman')),
                ('edition', models.CharField(blank=True, max_length=50, verbose_name='Cetakan / Edisi')),
                ('source_type', models.CharField(choices=[('Buku Fisik', 'Buku Fisik'), ('E-Book / PDF', 'E-Book / PDF'), ('Artikel / Jurnal Teknis', 'Artikel / Jurnal Teknis'), ('Dokumentasi Resmi', 'Dokumentasi Resmi / Standard')], default='Buku Fisik', max_length=50, verbose_name='Jenis Sumber Bacaan')),
                ('summary', models.TextField(verbose_name='Rangkuman RESIK (Minimal 100 Kata)')),
                ('moral_message', models.TextField(verbose_name='Pesan Moral / Relevansi Software Engineering')),
                ('word_count', models.PositiveIntegerField(default=0, verbose_name='Jumlah Kata Rangkuman')),
                ('self_checklist', models.JSONField(blank=True, default=dict, verbose_name='Checklist Mandiri Siswa')),
                ('writing_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nilai Penulisan & Struktur (0-100)')),
                ('presentation_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nilai Pemahaman & Presentasi (0-100)')),
                ('final_score', models.FloatField(blank=True, null=True, verbose_name='Nilai Akhir')),
                ('teacher_feedback', models.TextField(blank=True, null=True, verbose_name='Catatan Evaluasi Guru')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Penilaian')),
                ('status', models.CharField(choices=[('submitted', 'Menunggu Review Guru'), ('graded', 'Sudah Dinilai Guru')], default='submitted', max_length=20, verbose_name='Status Penilaian')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_literasi_reports', to=settings.AUTH_USER_MODEL, verbose_name='Dinilai Oleh')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='literasi_reports', to='admin_panel.enrollmenttoken', verbose_name='Sesi Token (Opsional)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='literasi_reports', to=settings.AUTH_USER_MODEL, verbose_name='Siswa')),
            ],
            options={
                'verbose_name': 'Laporan Rabu Literasi (RESIK)',
                'verbose_name_plural': 'Daftar Laporan Literasi RESIK',
                'ordering': ['-report_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiterasiPeerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=5, verbose_name='Rating Bintang (1 - 5)')),
                ('comment', models.TextField(verbose_name='Ulasan / Apresiasi Feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_peer_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Reviewer (Teman Sekelas)')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews', to='literasi.literasireport', verbose_name='Laporan Literasi')),
            ],
            options={
                'verbose_name': 'Peer Review Literasi',
                'verbose_name_plural': 'Daftar Peer Review Literasi',
                'ordering': ['-created_at'],
                'unique_together': {('report', 'reviewer')},
            },
        ),
        migrations.DeleteModel(
            name='LaporanLiterasi',
        ),
    ]
