# Generated by Django 5.1.15 on 2026-08-28 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='XPHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Jumlah XP')),
                ('category', models.CharField(choices=[('modul', 'Penyelesaian Modul'), ('lkpd', 'Pengumpulan LKPD'), ('tka', 'Simulasi CBT TKA'), ('literasi', 'Rabu Literasi RESIK'), ('streak', 'Daily Streak Bonus'), ('teacher', 'Apresiasi Guru')], max_length=20, verbose_name='Kategori Perolehan')),
                ('description', models.CharField(max_length=255, verbose_name='Keterangan Aktivitas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Riwayat XP',
                'verbose_name_plural': 'Daftar Riwayat XP',
                'ordering': ['-created_at'],
            },
        ),
    ]
