# Generated by Django 5.1.15 on 2026-08-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True, verbose_name='Kode Modul (e.g. MOD-01)')),
                ('judul', models.CharField(max_length=255, verbose_name='Judul Modul')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('deskripsi', models.TextField(verbose_name='Deskripsi Singkat')),
                ('urutan', models.PositiveIntegerField(default=1, verbose_name='Urutan')),
                ('xp_reward', models.PositiveIntegerField(default=100, verbose_name='Reward XP')),
                ('is_published', models.BooleanField(default=True, verbose_name='Status Publikasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modul Pembelajaran',
                'verbose_name_plural': 'Daftar Modul Pembelajaran',
                'ordering': ['urutan'],
            },
        ),
    ]
