# Generated by Django 5.1.15 on 2026-08-28 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('pembelajaran', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modul',
            name='xp_reward',
        ),
        migrations.AddField(
            model_name='modul',
            name='content_materi',
            field=models.TextField(blank=True, verbose_name='Konten Materi (Markdown / HTML)'),
        ),
        migrations.AddField(
            model_name='modul',
            name='durasi',
            field=models.CharField(default='2 JP (90 Menit)', max_length=50, verbose_name='Estimasi Durasi'),
        ),
        migrations.AddField(
            model_name='modul',
            name='kategori',
            field=models.CharField(default='Orientasi PPLG', max_length=100, verbose_name='Kategori / Elemen'),
        ),
        migrations.AddField(
            model_name='modul',
            name='level',
            field=models.CharField(default='Pemula', max_length=50, verbose_name='Tingkat Kesulitan'),
        ),
        migrations.AddField(
            model_name='modul',
            name='teacher_tip',
            field=models.TextField(blank=True, null=True, verbose_name='Tips & Catatan Pak Agung'),
        ),
        migrations.AddField(
            model_name='modul',
            name='xp_lkpd',
            field=models.PositiveIntegerField(default=25, verbose_name='Reward XP Submisi LKPD'),
        ),
        migrations.AddField(
            model_name='modul',
            name='xp_materi',
            field=models.PositiveIntegerField(default=10, verbose_name='Reward XP Baca Materi'),
        ),
        migrations.AddField(
            model_name='modul',
            name='xp_reflection',
            field=models.PositiveIntegerField(default=15, verbose_name='Reward XP Jurnal Refleksi'),
        ),
        migrations.AlterField(
            model_name='modul',
            name='kode',
            field=models.CharField(max_length=20, unique=True, verbose_name='Kode Modul (e.g. OR-01)'),
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Ditandai Selesai')),
                ('modul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='pembelajaran.modul', verbose_name='Modul')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_records', to='admin_panel.enrollmenttoken', verbose_name='Sesi Token')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL, verbose_name='Siswa')),
            ],
            options={
                'verbose_name': 'Progres Modul Siswa',
                'verbose_name_plural': 'Daftar Progres Modul Siswa',
                'ordering': ['-completed_at'],
                'unique_together': {('user', 'modul')},
            },
        ),
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_type', models.CharField(choices=[('lkpd', 'Lembar Kerja Peserta Didik (LKPD)'), ('reflection', 'Jurnal Refleksi Pembelajaran'), ('kktp_self_assessment', 'Self-Assessment KKTP')], max_length=30, verbose_name='Tipe Submisi')),
                ('form_data', models.JSONField(blank=True, default=dict, verbose_name='Payload Jawaban Form')),
                ('drive_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Folder Google Drive Evidence')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Skor Otomatis / Poin')),
                ('teacher_score', models.IntegerField(blank=True, null=True, verbose_name='Nilai Guru (0-100)')),
                ('teacher_level', models.CharField(blank=True, choices=[('Level 0', 'Level 0 - Belum Terlihat'), ('Level 1', 'Level 1 - Mengenal'), ('Level 2', 'Level 2 - Mencoba (Target Minimal Sem. 1)'), ('Level 3', 'Level 3 - Mandiri'), ('Level 4', 'Level 4 - Mahir / Standar Industri')], max_length=30, null=True, verbose_name='Level Capaian KKTP')),
                ('teacher_feedback', models.TextField(blank=True, null=True, verbose_name='Catatan Evaluasi Guru')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Penilaian')),
                ('status', models.CharField(choices=[('submitted', 'Terkirim / Menunggu Penilaian'), ('graded', 'Sudah Dinilai Guru')], default='submitted', max_length=20, verbose_name='Status Penilaian')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Submisi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Waktu Diperbarui')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Dinilai Oleh')),
                ('modul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='pembelajaran.modul', verbose_name='Modul')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='admin_panel.enrollmenttoken', verbose_name='Sesi Token (Opsional)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Siswa')),
            ],
            options={
                'verbose_name': 'Submisi Siswa (LKPD/Refleksi)',
                'verbose_name_plural': 'Daftar Submisi Siswa',
                'ordering': ['-submitted_at'],
                'unique_together': {('user', 'modul', 'submission_type')},
            },
        ),
    ]
