# Generated by Django 5.1.15 on 2026-09-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembelajaran', '0002_remove_modul_xp_reward_modul_content_materi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Terkirim / Menunggu Penilaian'), ('graded', 'Sudah Dinilai Guru'), ('reviewed', 'Telah Ditinjau Guru'), ('verified', 'Terverifikasi')], default='submitted', max_length=20, verbose_name='Status Penilaian'),
        ),
        migrations.AlterField(
            model_name='usersubmission',
            name='teacher_level',
            field=models.CharField(blank=True, choices=[('Level 4 (Mahir & Mandiri ★★★)', 'Level 4 (Mahir & Mandiri ★★★) - Sangat Baik'), ('Level 3 (Mampu Membimbing ★★)', 'Level 3 (Mampu Membimbing ★★) - Baik'), ('Level 2 (Mencoba ★)', 'Level 2 (Mencoba ★) - Cukup (Target Minimal)'), ('Level 1 (Mulai Berkembang)', 'Level 1 (Mulai Berkembang) - Perlu Bimbingan'), ('Level 0 (Belum Berkembang)', 'Level 0 (Belum Berkembang) - Belum Tuntas'), ('Level 4', 'Level 4 - Mahir / Standar Industri'), ('Level 3', 'Level 3 - Mandiri'), ('Level 2', 'Level 2 - Mencoba (Target Minimal Sem. 1)'), ('Level 1', 'Level 1 - Mengenal'), ('Level 0', 'Level 0 - Belum Terlihat')], max_length=60, null=True, verbose_name='Level Capaian KKTP'),
        ),
    ]
