# Generated by Django 5.1.15 on 2026-09-08 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CpnsPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=30, unique=True, verbose_name='Kode Paket (e.g. SKD-BKN-01)')),
                ('judul', models.CharField(max_length=255, verbose_name='Judul Paket Ujian')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('tipe_ujian', models.CharField(choices=[('SKD', 'Seleksi Kompetensi Dasar (SKD)'), ('SKB', 'Seleksi Kompetensi Bidang (SKB)')], default='SKD', max_length=10, verbose_name='Tipe Seleksi')),
                ('kategori', models.CharField(choices=[('SIMULASI_LENGKAP', 'Simulasi Lengkap SKD BKN (110 Soal)'), ('SKB_GURU', 'SKB Guru & Tenaga Pendidik'), ('TWK', 'Drilling Khusus TWK'), ('TIU', 'Drilling Khusus TIU'), ('TKP', 'Drilling Khusus TKP')], default='SIMULASI_LENGKAP', max_length=50, verbose_name='Kategori Ujian')),
                ('durasi_menit', models.PositiveIntegerField(default=100, verbose_name='Durasi Ujian (Menit)')),
                ('passing_grade_twk', models.PositiveIntegerField(default=65, verbose_name='Ambang Batas TWK')),
                ('passing_grade_tiu', models.PositiveIntegerField(default=80, verbose_name='Ambang Batas TIU')),
                ('passing_grade_tkp', models.PositiveIntegerField(default=166, verbose_name='Ambang Batas TKP')),
                ('passing_grade_skb', models.PositiveIntegerField(default=70, verbose_name='Ambang Batas SKB')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi & Cakupan Materi')),
                ('urutan', models.PositiveIntegerField(default=1, verbose_name='Urutan Tampil')),
                ('xp_base', models.PositiveIntegerField(default=35, verbose_name='Base Reward XP')),
                ('is_published', models.BooleanField(default=True, verbose_name='Status Publikasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paket Soal CPNS',
                'verbose_name_plural': 'Daftar Paket Soal CPNS',
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='CpnsAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=64, verbose_name='ID Sesi Tamu')),
                ('mode', models.CharField(choices=[('SIMULASI_CAT', 'Simulasi CAT Resmi (100 Menit)'), ('DRILLING_BEBAS', 'Drilling Fleksibel Mandiri')], default='SIMULASI_CAT', max_length=20, verbose_name='Mode Ujian')),
                ('skor_twk', models.PositiveIntegerField(default=0, verbose_name='Skor TWK')),
                ('skor_tiu', models.PositiveIntegerField(default=0, verbose_name='Skor TIU')),
                ('skor_tkp', models.PositiveIntegerField(default=0, verbose_name='Skor TKP')),
                ('skor_skb', models.PositiveIntegerField(default=0, verbose_name='Skor SKB')),
                ('total_skor', models.PositiveIntegerField(default=0, verbose_name='Total Skor Akhir')),
                ('lulus_twk', models.BooleanField(default=False, verbose_name='Lolos PG TWK')),
                ('lulus_tiu', models.BooleanField(default=False, verbose_name='Lolos PG TIU')),
                ('lulus_tkp', models.BooleanField(default=False, verbose_name='Lolos PG TKP')),
                ('status_lulus', models.BooleanField(default=False, verbose_name='Status Lulus Passing Grade')),
                ('jawaban_peserta', models.JSONField(blank=True, default=dict, verbose_name='Jawaban Peserta {question_id: selected_key}')),
                ('waktu_detik', models.PositiveIntegerField(default=0, verbose_name='Waktu Pengerjaan (Detik)')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Selesai')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cpns_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Peserta')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='cpns.cpnspackage', verbose_name='Paket Soal')),
            ],
            options={
                'verbose_name': 'Riwayat Ujian CPNS',
                'verbose_name_plural': 'Daftar Riwayat Ujian CPNS',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='CpnsQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtes', models.CharField(choices=[('TWK', 'Tes Wawasan Kebangsaan'), ('TIU', 'Tes Inteligensi Umum'), ('TKP', 'Tes Karakteristik Pribadi'), ('SKB_GURU', 'SKB Guru & Tenaga Pendidik')], default='TWK', max_length=20, verbose_name='Subtes')),
                ('subtopik', models.CharField(blank=True, max_length=100, verbose_name='Subtopik / Pokok Bahasan')),
                ('urutan', models.PositiveIntegerField(default=1, verbose_name='Nomor Soal')),
                ('pertanyaan', models.TextField(verbose_name='Narasi Pertanyaan / Soal')),
                ('opsi_a', models.TextField(verbose_name='Pilihan A')),
                ('opsi_b', models.TextField(verbose_name='Pilihan B')),
                ('opsi_c', models.TextField(verbose_name='Pilihan C')),
                ('opsi_d', models.TextField(verbose_name='Pilihan D')),
                ('opsi_e', models.TextField(verbose_name='Pilihan E')),
                ('kunci_jawaban', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='A', max_length=1, verbose_name='Kunci Jawaban')),
                ('bobot_tkp', models.JSONField(blank=True, null=True, verbose_name='Bobot Nilai TKP (1 - 5)')),
                ('bedah_konsep', models.TextField(blank=True, verbose_name='Bedah Konsep & Landasan Teori')),
                ('alasan_pengecoh', models.TextField(blank=True, verbose_name='Analisis Opsi Pengecoh')),
                ('tips_cepat', models.TextField(blank=True, verbose_name='Tips Cepat & Pola Kata Kunci')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cpns.cpnspackage', verbose_name='Paket Soal')),
            ],
            options={
                'verbose_name': 'Butir Soal CPNS',
                'verbose_name_plural': 'Daftar Butir Soal CPNS',
                'ordering': ['urutan'],
                'unique_together': {('package', 'urutan')},
            },
        ),
    ]
