# Generated by Django 5.1.15 on 2026-08-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaketUjian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200, verbose_name='Judul Paket Ujian')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('deskripsi', models.TextField(blank=True, verbose_name='Petunjuk Pengerjaan')),
                ('durasi_menit', models.PositiveIntegerField(default=60, verbose_name='Durasi (Menit)')),
                ('kkm', models.PositiveIntegerField(default=75, verbose_name='KKM (Kriteria Ketercapaian Tujuan Pembelajaran)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Paket Ujian TKA',
                'verbose_name_plural': 'Daftar Paket Ujian TKA',
            },
        ),
    ]
