# Generated by Django 5.1.15 on 2026-08-28 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('tka', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TkaAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(default=1, verbose_name='Percobaan Ke-')),
                ('score', models.FloatField(default=0.0, verbose_name='Skor Akhir (0 - 100)')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='Total Soal')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name='Jawaban Benar')),
                ('wrong_answers', models.PositiveIntegerField(default=0, verbose_name='Jawaban Salah')),
                ('user_answers', models.JSONField(blank=True, default=dict, verbose_name='Pilihan Jawaban Siswa {question_id: answer_choice}')),
                ('xp_earned', models.PositiveIntegerField(default=0, verbose_name='Reward XP Didapat')),
                ('is_passed', models.BooleanField(default=False, verbose_name='Status Lulus (Skor >= KKM)')),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, verbose_name='Waktu Pengerjaan (Detik)')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Selesai')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tka_attempts', to='admin_panel.enrollmenttoken', verbose_name='Sesi Token (Opsional)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tka_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Siswa')),
            ],
            options={
                'verbose_name': 'Riwayat Ujian CBT TKA',
                'verbose_name_plural': 'Daftar Riwayat Ujian CBT TKA',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='TkaPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True, verbose_name='Kode Paket (e.g. TKA-01)')),
                ('judul', models.CharField(max_length=255, verbose_name='Judul Paket Drilling')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('kategori', models.CharField(default='Drilling TKA PPLG', max_length=100, verbose_name='Kategori Soal')),
                ('level', models.CharField(default='Lanjutan', max_length=50, verbose_name='Tingkat Kesulitan')),
                ('durasi_menit', models.PositiveIntegerField(default=60, verbose_name='Durasi Ujian (Menit)')),
                ('passing_grade', models.PositiveIntegerField(default=75, verbose_name='KKM / Passing Grade')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Petunjuk & Cakupan Materi')),
                ('content_materi', models.TextField(blank=True, verbose_name='Bedah Materi & Konsep Inti')),
                ('teacher_tip', models.TextField(blank=True, null=True, verbose_name='Tips & Catatan Guru')),
                ('urutan', models.PositiveIntegerField(default=1, verbose_name='Urutan')),
                ('xp_base', models.PositiveIntegerField(default=25, verbose_name='Base Reward XP')),
                ('is_published', models.BooleanField(default=True, verbose_name='Status Publikasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paket Soal TKA',
                'verbose_name_plural': 'Daftar Paket Soal TKA',
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='TkaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Teks Soal / Pertanyaan')),
                ('option_a', models.TextField(verbose_name='Pilihan A')),
                ('option_b', models.TextField(verbose_name='Pilihan B')),
                ('option_c', models.TextField(verbose_name='Pilihan C')),
                ('option_d', models.TextField(verbose_name='Pilihan D')),
                ('option_e', models.TextField(verbose_name='Pilihan E')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, verbose_name='Kunci Jawaban Benar')),
                ('explanation', models.TextField(blank=True, verbose_name='Pembahasan Soal & Kunci')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Subtopik / Topik')),
                ('urutan', models.PositiveIntegerField(default=1, verbose_name='Nomor Soal')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tka.tkapackage', verbose_name='Paket Soal')),
            ],
            options={
                'verbose_name': 'Butir Soal TKA',
                'verbose_name_plural': 'Daftar Butir Soal TKA',
                'ordering': ['urutan'],
                'unique_together': {('package', 'urutan')},
            },
        ),
        migrations.DeleteModel(
            name='PaketUjian',
        ),
        migrations.AddField(
            model_name='tkaattempt',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='tka.tkapackage', verbose_name='Paket Soal'),
        ),
    ]
