# Generated by Django 5.1.15 on 2026-08-28 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Contoh: RPL-7K9A atau X-RPL-1', max_length=32, unique=True, verbose_name='Kode Token Sesi')),
                ('title', models.CharField(help_text='Contoh: KBM Orientasi PPLG Semester Gasal', max_length=200, verbose_name='Judul Sesi / KBM')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi / Catatan Guru')),
                ('target_type', models.CharField(choices=[('all', 'Akses Penuh / Semua Sesi'), ('module', 'Modul Pembelajaran Tertentu'), ('tka', 'Simulasi CBT TKA')], default='all', max_length=20, verbose_name='Tipe Target Akses')),
                ('target_slug', models.CharField(blank=True, max_length=100, null=True, verbose_name='Slug Target (Modul / TKA)')),
                ('target_class', models.CharField(default='Semua Kelas', help_text='Contoh: X PPLG 1, XI RPL 1, XII RPL 1, atau Semua Kelas', max_length=50, verbose_name='Rombel / Kelas Sasaran')),
                ('max_uses', models.PositiveIntegerField(default=36, verbose_name='Kapasitas Maksimal Siswa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status Sesi Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Dibuat')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Batas Waktu Kadaluarsa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens_created', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh Guru')),
            ],
            options={
                'verbose_name': 'Token Sesi / Enrollment',
                'verbose_name_plural': 'Daftar Token Sesi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Bergabung')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_enrollments', to='admin_panel.enrollmenttoken', verbose_name='Token Sesi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Siswa')),
            ],
            options={
                'verbose_name': 'User Enrollment',
                'verbose_name_plural': 'Daftar User Enrollment',
                'ordering': ['-enrolled_at'],
                'unique_together': {('user', 'token')},
            },
        ),
    ]
