# Generated by Django 5.1.15 on 2026-08-28 03:38

import apps.admin_panel.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=apps.admin_panel.models.generate_token_code, max_length=16, unique=True, verbose_name='Kode Token')),
                ('kelas_target', models.CharField(max_length=50, verbose_name='Kelas Target (e.g. X RPL 1)')),
                ('max_uses', models.PositiveIntegerField(default=36, verbose_name='Maksimal Penggunaan (Kapasitas Kelas)')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Jumlah Digunakan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token Enrollment Siswa',
                'verbose_name_plural': 'Daftar Token Enrollment',
            },
        ),
    ]
